server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_library"
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: psang4845@gmail.com
    password: qdoxupmchwitqfbr # lưu ý: phải là app password, không phải mật khẩu đăng nhập Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service-dev
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
    title: API Document
    version: v1.0.0
    description: Server Dev
  license:
    name: API License
    url: https://en.wikipedia.org/wiki/Software_license
api:
  base-path: /api/v1/library

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

app:
  default-role-code: USER
  file-path: D:/import-error-report.xlsx